// in
// Auto-generated by bootstrap

class EventSourcedContext {
  constructor() {
    this.events = [];
    this.snapshots = new Map();
  }
  
  addEvent(event) {
    // Append event with id and timestamp
  }
  
  getState(atTime) {
    // Rebuild state from events up to atTime
  }
  
  replay(fromEventId) {
    // Replay events from specific point
  }
}

module.exports = in;
