// explainer
// Generated by bootstrap
// Prompt: Create AgentExplainer class with:

class Explainer {
  constructor() {
    // TODO: Initialize
  }
  
  // TODO: Implement methods from prompt
}

module.exports = Explainer;
