// saga
// Generated by bootstrap
// Prompt: Create WorkflowSaga class with:

class Saga {
  constructor() {
    // TODO: Initialize
  }
  
  // TODO: Implement methods from prompt
}

module.exports = Saga;
